### ISSUE TITLE
Custom element doesn't exist: browser-control-card.

### ISSUE THREAD

**Issue by kismomesz** [mathoudebine/homeassistant-browser-control-card#10]
After updating the Home Assistant in version 2023.2.4, it does not appear.
But it was released in 2022. 11.
![image](https://user-images.githubusercontent.com/73526533/219690971-225e36c7-af23-46cb-9e53-51eaf15d81c4.png)

**Comment by KennethLavrsen** [comment]
I now suddenly have the same issue.

**Comment by Lampyridae1984** [comment]
+1

**Comment by lecrams** [comment]
+1

Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**Comment by AlexQuaken** [comment]
+4, four more instancesm from yesterday

**Comment by AlexQuaken** [comment]
The card uses a component from an external source; for example, if there's no internet connection, it won't work either. It needs external access to download something, and I suppose this external source is down, which is why the card isn't launching.

**Comment by KennethLavrsen** [comment]
I only ever used the feature for reloading because on my iPad I cannot do control refresh and clearing cache for the site is a pain. So this component was nice for a one click refresh of all css and js

I unstalled it and installed Lovelace Html Card instead. With that I could add button in html that runs the javascript one liner to reload the page without using the cache.

**Comment by Lampyridae1984** [comment]
> I unstalled it and installed Lovelace Html Card instead. With that I could add button in html that runs the javascript one liner to reload the page without using the cache.

Interesting, I'm guessing you are using: location.reload(true)

Would you perhaps be willing to share your yaml for this implementation?

**Comment by KennethLavrsen** [comment]
Sure. After installing Lovelace HTML card from HACS I added this card

```
type: custom:html-card
content: |
  <p><b>Reload HTML</b></p>
  <p><button type="button" onClick="window.location.reload(true)">
   Window Reload Page
  </button></p>
  <p><button type="button" onClick="document.location.reload(true)">
   Document Reload Page
  </button></p>
```

I think the two does the same but I was not sure.

**Comment by Lampyridae1984** [comment]
> Sure. After installing Lovelace HTML card from HACS I added this card
> 
> ```
> type: custom:html-card
> content: |
>   <p><b>Reload HTML</b></p>
>   <p><button type="button" onClick="window.location.reload(true)">
>    Window Reload Page
>   </button></p>
>   <p><button type="button" onClick="document.location.reload(true)">
>    Document Reload Page
>   </button></p>
> ```
> 
> I think the two does the same but I was not sure.

Cheers! I was a bit unsure how to implement it, but this is definitely straight forward. Yeah, the second button probably is unnecessary, the first one does the job just fine.

I added haptic feedback and some CSS, so everything looks and works just as before. 👍🏻

**Comment by AlexQuaken** [comment]
> Sure. After installing Lovelace HTML card from HACS I added this card
> 
> ```
> type: custom:html-card
> content: |
>   <p><b>Reload HTML</b></p>
>   <p><button type="button" onClick="window.location.reload(true)">
>    Window Reload Page
>   </button></p>
>   <p><button type="button" onClick="document.location.reload(true)">
>    Document Reload Page
>   </button></p>
> ```
> 
> I think the two does the same but I was not sure.

You can suggest how to add zoom functionality as before two buttons + - 10%

**Comment by mathoudebine** [comment]
Hey everyone, thanks for the feedback! I was not notified of this issue, don't know why. I will try to fix it soon!

**Comment by mathoudebine** [comment]
Issue is now fixed in v1.3.1, it was due to a lit module upgrade because the version used in this card was not specified. Please update through HACS to get the fix.

**Comment by mathoudebine** [comment]
> The card uses a component from an external source; for example, if there's no internet connection, it won't work either. It needs external access to download something, and I suppose this external source is down, which is why the card isn't launching.

I agree using an external component is not ideal for offline devices. I will think about changing it to a local component if possible

**Comment by lecrams** [comment]
I replaced the JS with the new 1.3.1 and rebooted.
Still the same issue unfortunately

**Comment by mathoudebine** [comment]
> I replaced the JS with the new 1.3.1 and rebooted.
> Still the same issue unfortunately

If you are installing the .js manually you will need to clear your browser cache to reload it

**Comment by lecrams** [comment]
I used CTRL F5 to refresh so that should normally be enough

**Comment by mathoudebine** [comment]
Depending on your browser, you may need to use Ctrl+Shift+R or explicitly clear the cache at least for your HomeAssistant URL

**Comment by lecrams** [comment]
After upgrading to core 2023-10.4 the issue is back!

**Comment by mathoudebine** [comment]
I'm actually running core 2023.10.5 and the issue did not come back.
If you are installing this card manually from the .js, you need to tell HomeAssistant that there is a new version otherwise it will put the .js in cache and will not reload it.

When installing by HACS this is done automatically by adding a "hacstag" after the .js URL in resouces:
![image](https://github.com/mathoudebine/homeassistant-browser-control-card/assets/38615348/22a3d8ae-08b6-4117-8a5d-cd99b8c98d76)

You may need to do this manually: follow this answer https://community.home-assistant.io/t/lovelace-custom-card-not-updating/88602/5
It doesn't matter what is added after the URL (either a `v=` or `hacstag=` or anything), just that the value must change each time the .js is updated to clear the HomeAssistant cache.

**Comment by lecrams** [comment]
I was indeed installing it manually. That explains the behaviour.
I have removed it now also manually and reinstalled and now it is working again.

Thx for the explanation
